# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_tool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 292)
        Form.setStyleSheet("QPushButton{\n"
"    background-color: rgb(250,252,253);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    font-size:12pt;\n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"\n"
"\n"
"QCommandLinkButton{\n"
"    background-color: rgb(214,227,242);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    border-right: 1px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 1px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 0px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 0px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:hover { \n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:pressed { \n"
"    background-color: lightgray;\n"
"    border: 2px solid #888888;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 430, 274))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_5 = QtWidgets.QFrame(self.widget_4)
        self.line_5.setStyleSheet("border-bottom: 2px solid #888888;")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 1, 0, 1, 2)
        self.commandLinkButton_convert = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_convert.setEnabled(True)
        self.commandLinkButton_convert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_convert.setTabletTracking(False)
        self.commandLinkButton_convert.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_convert.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_convert.setToolTipDuration(-1)
        self.commandLinkButton_convert.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_convert.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../resources/icons/strategy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_convert.setIcon(icon)
        self.commandLinkButton_convert.setCheckable(True)
        self.commandLinkButton_convert.setChecked(False)
        self.commandLinkButton_convert.setAutoRepeat(False)
        self.commandLinkButton_convert.setAutoExclusive(False)
        self.commandLinkButton_convert.setAutoDefault(False)
        self.commandLinkButton_convert.setDefault(False)
        self.commandLinkButton_convert.setObjectName("commandLinkButton_convert")
        self.gridLayout_3.addWidget(self.commandLinkButton_convert, 0, 1, 1, 1)
        self.commandLinkButton_screenshoot = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_screenshoot.setEnabled(True)
        self.commandLinkButton_screenshoot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_screenshoot.setTabletTracking(False)
        self.commandLinkButton_screenshoot.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_screenshoot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_screenshoot.setToolTipDuration(-1)
        self.commandLinkButton_screenshoot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_screenshoot.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../resources/icons/PDF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_screenshoot.setIcon(icon1)
        self.commandLinkButton_screenshoot.setCheckable(True)
        self.commandLinkButton_screenshoot.setChecked(False)
        self.commandLinkButton_screenshoot.setAutoRepeat(False)
        self.commandLinkButton_screenshoot.setAutoExclusive(False)
        self.commandLinkButton_screenshoot.setAutoDefault(False)
        self.commandLinkButton_screenshoot.setDefault(False)
        self.commandLinkButton_screenshoot.setObjectName("commandLinkButton_screenshoot")
        self.gridLayout_3.addWidget(self.commandLinkButton_screenshoot, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.widget_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.commandLinkButton_convert.setText(_translate("Form", "格式转换"))
        self.commandLinkButton_convert.setDescription(_translate("Form", "视频文件类型转换"))
        self.commandLinkButton_screenshoot.setText(_translate("Form", "录屏"))
        self.commandLinkButton_screenshoot.setDescription(_translate("Form", "屏幕录制"))
