# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_item_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_file_item_widget(object):
    def setupUi(self, file_item_widget):
        file_item_widget.setObjectName("file_item_widget")
        file_item_widget.resize(668, 34)
        file_item_widget.setAcceptDrops(True)
        file_item_widget.setStyleSheet("QWidget{\n"
"    background: rgb(248,248,251);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-radius: 5px;\n"
"    border:none;\n"
"    padding:0px;\n"
"}\n"
"QPushButton:hover { \n"
"    color: rgb(148,133,247)\n"
"}\n"
"QCommandLinkButton{\n"
"    background-color: rgb(250,252,253);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    border:none;\n"
"}\n"
"QProgressBar{\n"
"    font-family: \'Arial Unicode MS\';\n"
"    height:22px;\n"
"    text-align:center;\n"
"    font-size:14px;\n"
"    color:black;\n"
"    border-radius:11px;\n"
"    background:#EBEEF5;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius:11px;\n"
"    background:qlineargradient(spread:pad,x1:0,y1:0,x2:1,y2:0,stop:0 #99ffff,stop:1 #9900ff);\n"
"}")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(file_item_widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_name = QtWidgets.QCheckBox(file_item_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_name.sizePolicy().hasHeightForWidth())
        self.checkBox_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_name.setFont(font)
        self.checkBox_name.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_name.setObjectName("checkBox_name")
        self.horizontalLayout_3.addWidget(self.checkBox_name)
        self.label_size = QtWidgets.QLabel(file_item_widget)
        self.label_size.setMinimumSize(QtCore.QSize(50, 0))
        self.label_size.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_size.setFont(font)
        self.label_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_size.setObjectName("label_size")
        self.horizontalLayout_3.addWidget(self.label_size)
        self.label_page_num = QtWidgets.QLabel(file_item_widget)
        self.label_page_num.setMinimumSize(QtCore.QSize(50, 0))
        self.label_page_num.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_page_num.setFont(font)
        self.label_page_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page_num.setObjectName("label_page_num")
        self.horizontalLayout_3.addWidget(self.label_page_num)
        self.widget_3 = QtWidgets.QWidget(file_item_widget)
        self.widget_3.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_start = QtWidgets.QSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_start.sizePolicy().hasHeightForWidth())
        self.spinBox_start.setSizePolicy(sizePolicy)
        self.spinBox_start.setMinimumSize(QtCore.QSize(46, 0))
        self.spinBox_start.setMaximumSize(QtCore.QSize(46, 16777215))
        self.spinBox_start.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_start.setMinimum(1)
        self.spinBox_start.setObjectName("spinBox_start")
        self.horizontalLayout_2.addWidget(self.spinBox_start)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(6, 0))
        self.label_2.setMaximumSize(QtCore.QSize(6, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_end = QtWidgets.QSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_end.sizePolicy().hasHeightForWidth())
        self.spinBox_end.setSizePolicy(sizePolicy)
        self.spinBox_end.setMinimumSize(QtCore.QSize(46, 0))
        self.spinBox_end.setMaximumSize(QtCore.QSize(46, 16777215))
        self.spinBox_end.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_end.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_end.setMinimum(1)
        self.spinBox_end.setObjectName("spinBox_end")
        self.horizontalLayout_2.addWidget(self.spinBox_end)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(file_item_widget)
        self.widget.setMinimumSize(QtCore.QSize(100, 0))
        self.widget.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.label_result = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        self.horizontalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(file_item_widget)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_open = QtWidgets.QPushButton(self.widget_2)
        self.btn_open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout.addWidget(self.btn_open)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_up = QtWidgets.QPushButton(self.widget_2)
        self.btn_up.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_up.setObjectName("btn_up")
        self.verticalLayout_2.addWidget(self.btn_up)
        self.btn_down = QtWidgets.QPushButton(self.widget_2)
        self.btn_down.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_down.setObjectName("btn_down")
        self.verticalLayout_2.addWidget(self.btn_down)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.btn_delete = QtWidgets.QPushButton(self.widget_2)
        self.btn_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.horizontalLayout_3.addWidget(self.widget_2)

        self.retranslateUi(file_item_widget)
        QtCore.QMetaObject.connectSlotsByName(file_item_widget)

    def retranslateUi(self, file_item_widget):
        _translate = QtCore.QCoreApplication.translate
        file_item_widget.setWindowTitle(_translate("file_item_widget", "Form"))
        self.checkBox_name.setText(_translate("file_item_widget", "名称"))
        self.label_size.setText(_translate("file_item_widget", "size"))
        self.label_page_num.setText(_translate("file_item_widget", "页数"))
        self.label_2.setText(_translate("file_item_widget", "-"))
        self.label_result.setText(_translate("file_item_widget", "TextLabel"))
        self.btn_open.setText(_translate("file_item_widget", "✘"))
        self.btn_up.setText(_translate("file_item_widget", "▲"))
        self.btn_down.setText(_translate("file_item_widget", "▼"))
        self.btn_delete.setText(_translate("file_item_widget", "✘"))
