# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_record_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 300)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 40, 355, 124))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.format_label = QtWidgets.QLabel(self.widget)
        self.format_label.setObjectName("format_label")
        self.gridLayout.addWidget(self.format_label, 0, 0, 1, 1)
        self.format_combo = QtWidgets.QComboBox(self.widget)
        self.format_combo.setObjectName("format_combo")
        self.format_combo.addItem("")
        self.format_combo.addItem("")
        self.gridLayout.addWidget(self.format_combo, 0, 1, 1, 3)
        self.fps_label = QtWidgets.QLabel(self.widget)
        self.fps_label.setObjectName("fps_label")
        self.gridLayout.addWidget(self.fps_label, 1, 0, 1, 1)
        self.fps_spin = QtWidgets.QSpinBox(self.widget)
        self.fps_spin.setObjectName("fps_spin")
        self.fps_spin.setRange(1, 60)  # 最小值为 1，最大值为 60
        self.fps_spin.setValue(20)    # 默认值为 30
        self.gridLayout.addWidget(self.fps_spin, 1, 1, 1, 3)
        self.path_label = QtWidgets.QLabel(self.widget)
        self.path_label.setObjectName("path_label")
        self.gridLayout.addWidget(self.path_label, 2, 0, 1, 1)
        self.path_edit = QtWidgets.QLineEdit(self.widget)
        self.path_edit.setObjectName("path_edit")
        self.gridLayout.addWidget(self.path_edit, 2, 1, 1, 2)
        self.browse_button = QtWidgets.QPushButton(self.widget)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 2, 3, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.widget)
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 3, 0, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.widget)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 3, 2, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.format_label.setText(_translate("Form", "录制格式："))
        self.format_combo.setItemText(0, _translate("Form", "mp4"))
        self.format_combo.setItemText(1, _translate("Form", "avi"))
        self.fps_label.setText(_translate("Form", "帧率："))
        self.path_label.setText(_translate("Form", "保存路径："))
        self.browse_button.setText(_translate("Form", "选择路径"))
        self.start_button.setText(_translate("Form", "开始录制"))
        self.stop_button.setText(_translate("Form", "结束录制"))
