# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'merge_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_merge_pdf_view(object):
    def setupUi(self, merge_pdf_view):
        merge_pdf_view.setObjectName("merge_pdf_view")
        merge_pdf_view.resize(345, 546)
        merge_pdf_view.setStyleSheet("QWidget{\n"
"    background: rgb(238,244,249);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(250,252,253);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:hover { \n"
"    background-color: lightgray;\n"
"}\n"
"QCommandLinkButton{\n"
"    background-color: rgb(250,252,253);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    border:none;\n"
"}\n"
"QProgressBar{\n"
"    font-family: \'Arial Unicode MS\';\n"
"    height:22px;\n"
"    text-align:center;\n"
"    font-size:14px;\n"
"    color:black;\n"
"    border-radius:11px;\n"
"    background:#EBEEF5;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius:11px;\n"
"    background:qlineargradient(spread:pad,x1:0,y1:0,x2:1,y2:0,stop:0 #99ffff,stop:1 #9900ff);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(merge_pdf_view)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(merge_pdf_view)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.line_7 = QtWidgets.QFrame(merge_pdf_view)
        self.line_7.setStyleSheet("border-bottom: 2px solid #888888;")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_7.setLineWidth(5)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.label_7 = QtWidgets.QLabel(merge_pdf_view)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.btn_choose_files = QtWidgets.QPushButton(merge_pdf_view)
        self.btn_choose_files.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_choose_files.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_choose_files.setObjectName("btn_choose_files")
        self.verticalLayout.addWidget(self.btn_choose_files)
        self.list_view = QtWidgets.QListView(merge_pdf_view)
        self.list_view.setStyleSheet("QListView {\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"QListView::item {\n"
"    margin: 0px;\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QListView::item:hover {\n"
"    background: rgb(230, 235, 240);\n"
"}\n"
"/* 被选中时的背景颜色和左边框颜色 */\n"
"QListView::item:selected {\n"
"    border-radius: 0px;\n"
"    background: rgb(230, 235, 240);\n"
"}\n"
"")
        self.list_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_view.setObjectName("list_view")
        self.verticalLayout.addWidget(self.list_view)
        self.progressBar = QtWidgets.QProgressBar(merge_pdf_view)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_order_by_name = QtWidgets.QPushButton(merge_pdf_view)
        self.btn_order_by_name.setObjectName("btn_order_by_name")
        self.horizontalLayout.addWidget(self.btn_order_by_name)
        self.btn_order_by_time = QtWidgets.QPushButton(merge_pdf_view)
        self.btn_order_by_time.setObjectName("btn_order_by_time")
        self.horizontalLayout.addWidget(self.btn_order_by_time)
        self.btn_merge = QtWidgets.QPushButton(merge_pdf_view)
        self.btn_merge.setObjectName("btn_merge")
        self.horizontalLayout.addWidget(self.btn_merge)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(merge_pdf_view)
        QtCore.QMetaObject.connectSlotsByName(merge_pdf_view)

    def retranslateUi(self, merge_pdf_view):
        _translate = QtCore.QCoreApplication.translate
        merge_pdf_view.setWindowTitle(_translate("merge_pdf_view", "Form"))
        self.label_8.setText(_translate("merge_pdf_view", "合并多个PDF"))
        self.label_7.setText(_translate("merge_pdf_view", "选择所需的PDF"))
        self.btn_choose_files.setText(_translate("merge_pdf_view", "Choose files"))
        self.btn_order_by_name.setText(_translate("merge_pdf_view", "按名称排序"))
        self.btn_order_by_time.setText(_translate("merge_pdf_view", "按日期排序"))
        self.btn_merge.setText(_translate("merge_pdf_view", "合并"))
