# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_tool_ui.ui'
#
# Created by: PySide6 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 292)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        Form.setStyleSheet("QPushButton{\n"
"    background-color: rgb(250,252,253);\n"
"    border-radius: 5px;\n"
"    font-size:12pt;\n"
"    padding: 8px;\n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"\n"
"\n"
"QCommandLinkButton{\n"
"    background-color: rgb(214,227,242);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    border-right: 1px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 1px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 0px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 0px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:hover { \n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:pressed { \n"
"    background-color: lightgray;\n"
"    border: 2px solid #888888;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 430, 274))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_8 = QtWidgets.QFrame(self.widget_4)
        self.line_8.setStyleSheet("border-bottom: 2px solid #888888;")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_8.setLineWidth(5)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 1, 0, 1, 2)
        self.commandLinkButton_modify_name_by_time = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_modify_name_by_time.setEnabled(True)
        self.commandLinkButton_modify_name_by_time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_modify_name_by_time.setTabletTracking(False)
        self.commandLinkButton_modify_name_by_time.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_modify_name_by_time.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_modify_name_by_time.setToolTipDuration(-1)
        self.commandLinkButton_modify_name_by_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_modify_name_by_time.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../resources/icons/strategy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_modify_name_by_time.setIcon(icon)
        self.commandLinkButton_modify_name_by_time.setCheckable(True)
        self.commandLinkButton_modify_name_by_time.setChecked(False)
        self.commandLinkButton_modify_name_by_time.setAutoRepeat(False)
        self.commandLinkButton_modify_name_by_time.setAutoExclusive(False)
        self.commandLinkButton_modify_name_by_time.setAutoDefault(False)
        self.commandLinkButton_modify_name_by_time.setDefault(False)
        self.commandLinkButton_modify_name_by_time.setObjectName("commandLinkButton_modify_name_by_time")
        self.gridLayout_3.addWidget(self.commandLinkButton_modify_name_by_time, 0, 1, 1, 1)
        self.commandLinkButton_modify_date = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_modify_date.setEnabled(True)
        self.commandLinkButton_modify_date.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_modify_date.setTabletTracking(False)
        self.commandLinkButton_modify_date.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_modify_date.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_modify_date.setToolTipDuration(-1)
        self.commandLinkButton_modify_date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_modify_date.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../resources/icons/PDF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_modify_date.setIcon(icon1)
        self.commandLinkButton_modify_date.setCheckable(True)
        self.commandLinkButton_modify_date.setChecked(False)
        self.commandLinkButton_modify_date.setAutoRepeat(False)
        self.commandLinkButton_modify_date.setAutoExclusive(False)
        self.commandLinkButton_modify_date.setAutoDefault(False)
        self.commandLinkButton_modify_date.setDefault(False)
        self.commandLinkButton_modify_date.setObjectName("commandLinkButton_modify_date")
        self.gridLayout_3.addWidget(self.commandLinkButton_modify_date, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.widget_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.commandLinkButton_modify_name_by_time.setText(_translate("Form", "重命名"))
        self.commandLinkButton_modify_name_by_time.setDescription(_translate("Form", "根据拍摄日期修改文件名"))
        self.commandLinkButton_modify_date.setText(_translate("Form", "修改拍摄日期"))
        self.commandLinkButton_modify_date.setDescription(_translate("Form", "根据文件名修改图片的拍摄日期"))
