# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(250, 92)
        Form.setMaximumSize(QtCore.QSize(250, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_avatar = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_avatar.sizePolicy().hasHeightForWidth())
        self.label_avatar.setSizePolicy(sizePolicy)
        self.label_avatar.setMinimumSize(QtCore.QSize(45, 45))
        self.label_avatar.setMaximumSize(QtCore.QSize(45, 45))
        self.label_avatar.setObjectName("label_avatar")
        self.gridLayout.addWidget(self.label_avatar, 0, 0, 2, 1)
        self.label_nickname = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nickname.sizePolicy().hasHeightForWidth())
        self.label_nickname.setSizePolicy(sizePolicy)
        self.label_nickname.setObjectName("label_nickname")
        self.gridLayout.addWidget(self.label_nickname, 0, 1, 1, 1)
        self.label_time = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time.sizePolicy().hasHeightForWidth())
        self.label_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 0, 2, 1, 1)
        self.label_content = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_content.setFont(font)
        self.label_content.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_content.setObjectName("label_content")
        self.gridLayout.addWidget(self.label_content, 1, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_avatar.setText(_translate("Form", "TextLabel"))
        self.label_nickname.setText(_translate("Form", "TextLabel"))
        self.label_time.setText(_translate("Form", "24/3/17"))
        self.label_content.setText(_translate("Form", "TextLabel"))
