# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdf_tool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 292)
        Form.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 430, 274))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(250,252,253);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"\n"
"\n"
"QCommandLinkButton{\n"
"    background-color: rgb(214,227,242);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    border-right: 1px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 1px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 0px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 0px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:hover { \n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:pressed { \n"
"    background-color: lightgray;\n"
"    border: 2px solid #888888;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_5 = QtWidgets.QFrame(self.widget_4)
        self.line_5.setStyleSheet("border-bottom: 2px solid #888888;")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 3, 0, 1, 2)
        self.line_7 = QtWidgets.QFrame(self.widget_4)
        self.line_7.setStyleSheet("border-bottom: 2px solid #888888;")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_7.setLineWidth(5)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout_3.addWidget(self.line_7, 6, 0, 1, 2)
        self.commandLinkButton_encrypt = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_encrypt.setEnabled(True)
        self.commandLinkButton_encrypt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_encrypt.setTabletTracking(False)
        self.commandLinkButton_encrypt.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_encrypt.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_encrypt.setToolTipDuration(-1)
        self.commandLinkButton_encrypt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_encrypt.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../resources/icons/random.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_encrypt.setIcon(icon)
        self.commandLinkButton_encrypt.setCheckable(True)
        self.commandLinkButton_encrypt.setChecked(False)
        self.commandLinkButton_encrypt.setAutoRepeat(False)
        self.commandLinkButton_encrypt.setAutoExclusive(False)
        self.commandLinkButton_encrypt.setAutoDefault(False)
        self.commandLinkButton_encrypt.setDefault(False)
        self.commandLinkButton_encrypt.setObjectName("commandLinkButton_encrypt")
        self.gridLayout_3.addWidget(self.commandLinkButton_encrypt, 2, 0, 1, 1)
        self.commandLinkButton_decrypt = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_decrypt.setEnabled(True)
        self.commandLinkButton_decrypt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_decrypt.setTabletTracking(False)
        self.commandLinkButton_decrypt.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_decrypt.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_decrypt.setToolTipDuration(-1)
        self.commandLinkButton_decrypt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_decrypt.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../resources/icons/ratio.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_decrypt.setIcon(icon1)
        self.commandLinkButton_decrypt.setCheckable(False)
        self.commandLinkButton_decrypt.setChecked(False)
        self.commandLinkButton_decrypt.setAutoRepeat(False)
        self.commandLinkButton_decrypt.setAutoExclusive(False)
        self.commandLinkButton_decrypt.setAutoDefault(False)
        self.commandLinkButton_decrypt.setDefault(False)
        self.commandLinkButton_decrypt.setObjectName("commandLinkButton_decrypt")
        self.gridLayout_3.addWidget(self.commandLinkButton_decrypt, 2, 1, 1, 1)
        self.commandLinkButton_delete_blank_pages = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_delete_blank_pages.setEnabled(True)
        self.commandLinkButton_delete_blank_pages.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_delete_blank_pages.setTabletTracking(False)
        self.commandLinkButton_delete_blank_pages.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_delete_blank_pages.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_delete_blank_pages.setToolTipDuration(-1)
        self.commandLinkButton_delete_blank_pages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_delete_blank_pages.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../resources/icons/strategy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_delete_blank_pages.setIcon(icon2)
        self.commandLinkButton_delete_blank_pages.setCheckable(True)
        self.commandLinkButton_delete_blank_pages.setChecked(False)
        self.commandLinkButton_delete_blank_pages.setAutoRepeat(False)
        self.commandLinkButton_delete_blank_pages.setAutoExclusive(False)
        self.commandLinkButton_delete_blank_pages.setAutoDefault(False)
        self.commandLinkButton_delete_blank_pages.setDefault(False)
        self.commandLinkButton_delete_blank_pages.setObjectName("commandLinkButton_delete_blank_pages")
        self.gridLayout_3.addWidget(self.commandLinkButton_delete_blank_pages, 5, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.widget_4)
        self.line_8.setStyleSheet("border-bottom: 2px solid #888888;")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_8.setLineWidth(5)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 1, 0, 1, 2)
        self.commandLinkButton_merge_pdf = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_merge_pdf.setEnabled(True)
        self.commandLinkButton_merge_pdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_merge_pdf.setTabletTracking(False)
        self.commandLinkButton_merge_pdf.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_merge_pdf.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_merge_pdf.setToolTipDuration(-1)
        self.commandLinkButton_merge_pdf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_merge_pdf.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../resources/icons/PDF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_merge_pdf.setIcon(icon3)
        self.commandLinkButton_merge_pdf.setCheckable(True)
        self.commandLinkButton_merge_pdf.setChecked(False)
        self.commandLinkButton_merge_pdf.setAutoRepeat(False)
        self.commandLinkButton_merge_pdf.setAutoExclusive(False)
        self.commandLinkButton_merge_pdf.setAutoDefault(False)
        self.commandLinkButton_merge_pdf.setDefault(False)
        self.commandLinkButton_merge_pdf.setObjectName("commandLinkButton_merge_pdf")
        self.gridLayout_3.addWidget(self.commandLinkButton_merge_pdf, 0, 0, 1, 1)
        self.commandLinkButton_split_pdf = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_split_pdf.setEnabled(True)
        self.commandLinkButton_split_pdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_split_pdf.setTabletTracking(False)
        self.commandLinkButton_split_pdf.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_split_pdf.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_split_pdf.setToolTipDuration(-1)
        self.commandLinkButton_split_pdf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_split_pdf.setAutoFillBackground(False)
        self.commandLinkButton_split_pdf.setIcon(icon2)
        self.commandLinkButton_split_pdf.setCheckable(True)
        self.commandLinkButton_split_pdf.setChecked(False)
        self.commandLinkButton_split_pdf.setAutoRepeat(False)
        self.commandLinkButton_split_pdf.setAutoExclusive(False)
        self.commandLinkButton_split_pdf.setAutoDefault(False)
        self.commandLinkButton_split_pdf.setDefault(False)
        self.commandLinkButton_split_pdf.setObjectName("commandLinkButton_split_pdf")
        self.gridLayout_3.addWidget(self.commandLinkButton_split_pdf, 0, 1, 1, 1)
        self.commandLinkButton_add_watermark = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_add_watermark.setObjectName("commandLinkButton_add_watermark")
        self.gridLayout_3.addWidget(self.commandLinkButton_add_watermark, 5, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.widget_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.commandLinkButton_encrypt.setText(_translate("Form", "PDF加密"))
        self.commandLinkButton_encrypt.setDescription(_translate("Form", "设置PDF打开、编辑密码"))
        self.commandLinkButton_decrypt.setText(_translate("Form", "PDF解密"))
        self.commandLinkButton_decrypt.setDescription(_translate("Form", "从PDF文档中移除密码保护"))
        self.commandLinkButton_delete_blank_pages.setText(_translate("Form", "删除空白页"))
        self.commandLinkButton_delete_blank_pages.setDescription(_translate("Form", "批量删除PDF文件中的空白页"))
        self.commandLinkButton_merge_pdf.setText(_translate("Form", "合并"))
        self.commandLinkButton_merge_pdf.setDescription(_translate("Form", "合并多个PDF为一个"))
        self.commandLinkButton_split_pdf.setText(_translate("Form", "拆分"))
        self.commandLinkButton_split_pdf.setDescription(_translate("Form", "把一个PDF拆分成多个"))
        self.commandLinkButton_add_watermark.setText(_translate("Form", "添加水印"))
        self.commandLinkButton_add_watermark.setDescription(_translate("Form", "在PDF中添加自定义水印"))
