# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enhance_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 839)
        Form.setStyleSheet("QPushButton{\n"
"    background-color: rgb(250,252,253);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    font-size:12pt;\n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"\n"
"\n"
"QCommandLinkButton{\n"
"    background-color: rgb(214,227,242);\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    border-right: 1px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 1px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 0px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 0px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:hover { \n"
"    border-right: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-bottom: 2px solid #888888;  /* 按钮边框，2px宽，白色 */\n"
"    border-left: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"    border-top: 1px solid #ffffff;  /* 按钮边框，2px宽，白色 */\n"
"}\n"
"QPushButton:pressed { \n"
"    background-color: lightgray;\n"
"    border: 2px solid #888888;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 430, 821))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.commandLinkButton_toc = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_toc.setEnabled(True)
        self.commandLinkButton_toc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_toc.setTabletTracking(False)
        self.commandLinkButton_toc.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_toc.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_toc.setToolTipDuration(-1)
        self.commandLinkButton_toc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_toc.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../resources/icons/strategy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_toc.setIcon(icon)
        self.commandLinkButton_toc.setCheckable(True)
        self.commandLinkButton_toc.setChecked(False)
        self.commandLinkButton_toc.setAutoRepeat(False)
        self.commandLinkButton_toc.setAutoExclusive(False)
        self.commandLinkButton_toc.setAutoDefault(False)
        self.commandLinkButton_toc.setDefault(False)
        self.commandLinkButton_toc.setObjectName("commandLinkButton_toc")
        self.gridLayout_3.addWidget(self.commandLinkButton_toc, 0, 1, 1, 1)
        self.commandLinkButton_pdf2word = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_pdf2word.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton_pdf2word.sizePolicy().hasHeightForWidth())
        self.commandLinkButton_pdf2word.setSizePolicy(sizePolicy)
        self.commandLinkButton_pdf2word.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_pdf2word.setTabletTracking(False)
        self.commandLinkButton_pdf2word.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_pdf2word.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_pdf2word.setToolTipDuration(-1)
        self.commandLinkButton_pdf2word.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_pdf2word.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../resources/icons/PDF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_pdf2word.setIcon(icon1)
        self.commandLinkButton_pdf2word.setCheckable(True)
        self.commandLinkButton_pdf2word.setChecked(False)
        self.commandLinkButton_pdf2word.setAutoRepeat(False)
        self.commandLinkButton_pdf2word.setAutoExclusive(False)
        self.commandLinkButton_pdf2word.setAutoDefault(False)
        self.commandLinkButton_pdf2word.setDefault(False)
        self.commandLinkButton_pdf2word.setObjectName("commandLinkButton_pdf2word")
        self.gridLayout_3.addWidget(self.commandLinkButton_pdf2word, 0, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.widget_4)
        self.line_8.setStyleSheet("border-bottom: 2px solid #888888;")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_8.setLineWidth(5)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 1, 0, 1, 2)
        self.commandLinkButton_pdf2txt = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_pdf2txt.setEnabled(True)
        self.commandLinkButton_pdf2txt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_pdf2txt.setTabletTracking(False)
        self.commandLinkButton_pdf2txt.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_pdf2txt.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_pdf2txt.setToolTipDuration(-1)
        self.commandLinkButton_pdf2txt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_pdf2txt.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../resources/icons/random.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_pdf2txt.setIcon(icon2)
        self.commandLinkButton_pdf2txt.setCheckable(True)
        self.commandLinkButton_pdf2txt.setChecked(False)
        self.commandLinkButton_pdf2txt.setAutoRepeat(False)
        self.commandLinkButton_pdf2txt.setAutoExclusive(False)
        self.commandLinkButton_pdf2txt.setAutoDefault(False)
        self.commandLinkButton_pdf2txt.setDefault(False)
        self.commandLinkButton_pdf2txt.setObjectName("commandLinkButton_pdf2txt")
        self.gridLayout_3.addWidget(self.commandLinkButton_pdf2txt, 2, 0, 1, 1)
        self.commandLinkButton_pdf2excel = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_pdf2excel.setEnabled(True)
        self.commandLinkButton_pdf2excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_pdf2excel.setTabletTracking(False)
        self.commandLinkButton_pdf2excel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.commandLinkButton_pdf2excel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.commandLinkButton_pdf2excel.setToolTipDuration(-1)
        self.commandLinkButton_pdf2excel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_pdf2excel.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../resources/icons/ratio.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_pdf2excel.setIcon(icon3)
        self.commandLinkButton_pdf2excel.setCheckable(False)
        self.commandLinkButton_pdf2excel.setChecked(False)
        self.commandLinkButton_pdf2excel.setAutoRepeat(False)
        self.commandLinkButton_pdf2excel.setAutoExclusive(False)
        self.commandLinkButton_pdf2excel.setAutoDefault(False)
        self.commandLinkButton_pdf2excel.setDefault(False)
        self.commandLinkButton_pdf2excel.setObjectName("commandLinkButton_pdf2excel")
        self.gridLayout_3.addWidget(self.commandLinkButton_pdf2excel, 2, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.widget_4)
        self.line_5.setStyleSheet("border-bottom: 2px solid #888888;")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 3, 0, 1, 2)
        self.verticalLayout_8.addWidget(self.widget_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.commandLinkButton_toc.setText(_translate("Form", "生成PDF目录"))
        self.commandLinkButton_toc.setDescription(_translate("Form", "按日期生成PDF书签目录"))
        self.commandLinkButton_pdf2word.setText(_translate("Form", "PDF转Word"))
        self.commandLinkButton_pdf2word.setDescription(_translate("Form", "将PDF转为Word格式"))
        self.commandLinkButton_pdf2txt.setText(_translate("Form", "PDF转文本"))
        self.commandLinkButton_pdf2txt.setDescription(_translate("Form", "将PDF转换为文本格式"))
        self.commandLinkButton_pdf2excel.setText(_translate("Form", "PDF转Excel"))
        self.commandLinkButton_pdf2excel.setDescription(_translate("Form", "提取出PDF中的表格并将其转换为Excel"))
